# -*- coding: utf-8 -*-
"""Copy of Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XqpPq3AMiVNYEYPtAunvmztiYIkI2OJ
"""

# Practising the previous class programs and starting
# with Python_function concept today in data science

# question 1
arr = []
for i in range(5):
  arr.append(int(input("Enter the numbers: ")))
print(arr)

# Doing it in some another way
arr = [int(input("Enter the numbers: ")) for i in range(5)]
print(arr)

# Question 2
brr = [i for i in range(0, 100) if i % 2 == 0]
print(brr)

# Question 3
# fruits = ["mangoes","apples","grapes","kiwi"]
# new_list = [i for i in fruits if i != "mangoes"]
# print(new_list)

# Question 4
for i in range(5):
  for j in range(5):
    print(j)

# Question 5
# Nested if else
num = int(input("Enter your range: "))
if num > 1000:
  if num < 10000:
    if num == 5000:
      print("This number is exactly 5000")
    print("Thanks for entering your number....")
  print("This is an integer number....")
else:
  print("I am wrong")

# Question 6
ab = [1,2,3,4]

for i in ab:
  print("Hello Users")

# Question 7
# Using the zip functions we can zip the two list
fruits = ['apples','mangoes','bananas','kiwi']
quantity = [5,4,3,4]

final = {}

for i,j in zip(fruits , quantity):
  final[i] = j
print(final)

# Question 8
for i in range(10):
  print("Sorry mam I won't do it again in my class")

# Question 9
# factorial program

num = int(input("Enter the number: "))
var = 1

for i in range(1 , num+1):
  if num < 0:
    print("The input is invalid")
  elif num == 1 or num == 0:
    print("The factorial is 1")
  else:
    var = var * i
print(var)

# Question 10
# String case convertion

string = input("Enter the string over here: ")

for i in string:
  if i.isupper():
    print(i.lower(), end="")
  else:
    print(i.upper(), end="")

# Another method is also there
print(input("Enter the string: ").swapcase())

# Question 11
# palindrom number
x = input("Enter the input: ").lower()

new_x = reversed(x)
# print(new_x)

if list(x) == list(new_x):
  print("The input is Palindrom !")
else:
  print("The input is not Palindrom !")

# Another way to do this same palindrom program is that
x = input("Enter any string or number: ").lower()

new_x = x[::-1]
if x == new_x:
  print("The input is Palindrom")
else:
  print("The input is not Palindrom")

# Question 12
# Replace function use
string = input("Enter the string: ")

string1 = string.replace("Bisso","Hrithik")

print(string1)

# Starting with functions and its concept
a = int(input())
if a == 10:
  print("Something")
else:
  print("Nothing")

def first_function():
  a = int(input())
  if a == 10:
    print("something !")
  else:
    print("nothing !")

# 10000 lines of code
first_function()

def addition():
  a = int(input("Enter the first number: "))
  b = int(input("Enter the second number: "))
  c = int(input("Enter the third number: "))

  print(a+b+c)
  return a+b+c

variable = addition()

# There are three types of function
# 1. Parameters -> len(),sum(),range(),max()
# 2. Doesn,t takes any parameters -> popitems(),upper(),lower(),isapha()
# 3. Default Parameter -> popitems()

# Parameterize function
def addition(a,b):
  return a+b

poll = addition(2,8)

print(poll)

# Default Parameterize function
def addition(a,b=10):
  # print(a+b)
  return a+b

print(addition(8,2))

# A function -> age(input)
 # if age > 60 -> old
 # if the age is b/w 30 to 60 -> middle aged
 # if the age is b/w 19 to 30 -> young
 # if the age is b/w 13 to 19 -> Teen
 # else -> kid

# Writing the script over here :
def age_program(age):
  if age > 60:
    print("This person is old !")
  elif age > 30 and age <= 60:
    print("This person is middle aged !")
  elif age > 19 and age <= 30:
    print("This person is young")
  elif age >= 13 and age <= 19:
    print("This person is teen")
  else:
    print("You are a kid")
    # return(age)

age_program(int(input("Enter your age: ")))

# We can write the script like this also:
# def age_program(age):
#   if age > 60:
#     print("This person is old !")
#   elif 30 < age <= 60:
#     print("This person is middle aged !")
#   elif 19 < age <= 30:
#     print("This person is young")
#   elif 13 < age <= 19:
#     print("This person is teen")
#   else:
#     print("You are a kid")
#     return(age)

# age_program(24)

# Advance concept of function
def advanced(a,b,c,d):
  return a+b-c*d

advanced(1,2,3,4)

# Precedence of the operators
# Bodmas

# *args and **kwargs (arbitary)
def advanced(*args):
  lis = list(args)
  return sum(lis)

advanced(1,2,3,4,5,6,7,8)

